### ISSUE TITLE
sh: ./crawler.coffee: No such file or directory 是怎么回事？

### ISSUE THREAD

**Issue by jerry011235** [monkeym4ster/imooc_crawler#1]
你好，我的电脑是win7,安装了Node.js和git，然后新建一个imooc_crawler文件夹，在里面用git bash下载了 git clone https://github.com/monkeym4ster/imooc_crawler ，然后npm是安装hexo博客时已经安装了的，npm －v显示2.11.3，问题是我在git bash（当前目录位置为imooc_crawler文件夹）里输入./crawler.coffee http://www.imooc.com/learn/514 时报错，显示
sh: ./crawler.coffee: No such file or directory 是怎么回事？谢谢！

**Comment by monkeym4ster** [comment]
请尝试安装CoffeeScript
> npm install coffee-script -g

安装完毕后使用coffee启动爬虫程序
> coffee crawler.coffee

感谢反馈 ：）

**Comment by jerry011235** [comment]
感谢回复！目前能运行node crawler.js，如下：
``` c
$ node crawler.js
Usage: crawler.js [Options]
  --search       Search for the specified keywords
  --list         List the video list under the specified course ID or URL
  --download     Download the video list under the specified course ID or URL
```
1.但是--search 和 --list 报错。
2.而 --download   能正常下载，但是下载完成也不跳到 等待命令输入的状态，希望加个实时下载速度和下载完成的提示。
``` c
$ node crawler.js --list 434
Read video list: http://www.imooc.com/learn/434
e:\imooc_crawler\crawler.js:211
        console.log('-'.repeat(30));
                        ^
TypeError: undefined is not a function
    at e:\imooc_crawler\crawler.js:211:25
    at Request._callback (e:\imooc_crawler\crawler.js:42:16)
    at Request.self.callback (e:\imooc_crawler\node_modules\request\request.js:1
98:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (e:\imooc_crawler\node_modules\request\request.js:108
2:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (e:\imooc_crawler\node_modules\request\reques
t.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Sunshine@SUNSHINE-PC /E/imooc_crawler
$ node crawler.js --download http://www.imooc.com/view/434
Read video list: http://www.imooc.com/view/434
```

``` c
$ node crawler.js --search node
Read course list: http://www.imooc.com/index/search?words=node&page=1
e:\imooc_crawler\crawler.js:211
        console.log('-'.repeat(30));
                        ^
TypeError: undefined is not a function
    at e:\imooc_crawler\crawler.js:211:25
    at Request._callback (e:\imooc_crawler\crawler.js:106:18)
    at Request.self.callback (e:\imooc_crawler\node_modules\request\request.js:1
98:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (e:\imooc_crawler\node_modules\request\request.js:108
2:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (e:\imooc_crawler\node_modules\request\reques
t.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by monkeym4ster** [comment]
1、已修复低版本 node 兼容问题；
2、已添加下载实时进度条。

**Comment by jerry011235** [comment]
谢谢！完美解决！
