### ISSUE TITLE
正则匹配错误

### ISSUE THREAD

**Issue by mgcnrx11** [monkeym4ster/imooc_crawler#2]
```
imooc_crawler-master  node crawler.js --download 337
Read video list: http://www.imooc.com/learn/337
Download course: 1-1 Oracle基础概述.mp4, url: http://www.imooc.com/course/ajaxmediainfo/?mode=flash&mid=6541
Download course: 1-2 Oracle安装.mp4, url: http://www.imooc.com/course/ajaxmediainfo/?mode=flash&mid=6542
Download course: 1-3 Oracle卸载.mp4, url: http://www.imooc.com/course/ajaxmediainfo/?mode=flash&mid=6543
Download course: 2-1 使用系统用户登录Oracle.mp4, url: http://www.imooc.com/course/ajaxmediainfo/?mode=flash&mid=6544
Download course: 2-2 查看登录用户.mp4, url: http://www.imooc.com/course/ajaxmediainfo/?mode=flash&mid=6545
Download course: 2-3 启用scott用户.mp4, url: http://www.imooc.com/course/ajaxmediainfo/?mode=flash&mid=6546
/Users/xxx/Downloads/imooc_crawler-master/crawler.js:64
    filename = video.name.match(/(.*)\s\(/)[1] + '.mp4';
                                           ^

TypeError: Cannot read property '1' of null
    at readVideoDetailAndDownload (/Users/xxx/Downloads/imooc_crawler-master/crawler.js:64:44)
    at /Users/xxx/Downloads/imooc_crawler-master/crawler.js:196:13
    at Request._callback (/Users/xxx/Downloads/imooc_crawler-master/crawler.js:46:16)
    at Request.self.callback (/Users/xxx/Downloads/imooc_crawler-master/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/xxx/Downloads/imooc_crawler-master/node_modules/request/request.js:1063:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/xxx/Downloads/imooc_crawler-master/node_modules/request/request.js:1009:12)

```

**Comment by monkeym4ster** [comment]
感谢反馈，已修复此问题 :-)
https://github.com/monkeym4ster/imooc_crawler/commit/63c2f85b01be54b493ad9451c17f2d39b2d81d4c
